### PR TITLE
Submitting exercise04

### PR DESCRIPTION
**Pull request by aander222**

### CODE REVIEW

**Review by chesterharvey — CHANGES_REQUESTED** [review]
I'm finally getting to looking through the PRs, and the .ipynb file in yours is blank. My hunch is that this is related to the VSCode issue you mentioned in class. Any chance you have a local copy of the notebook file you could commit to the PR?

When I look at your fork (screenshot below) it seems like the notebook was blank right from the initial commit.

image

**Comment by chesterharvey** [comment]
The code in your module looks good, though! If you don't have the notebook anymore, I'll import the module and try to provide the right arguments to your main function.

**Comment by aander222** [comment]
Chester,
Does this file work for you? If it does, I can commit it to GitHub when I
get back from my appointment.

**Comment by chesterharvey** [comment]
Unfortunately, I don't think attachments work when replying to github comments by email. If you can commit it later today, or send it to my email, that might work better. No particular rush.

**Comment by chesterharvey** [comment]
Thanks for emailing the notebook. I'm a little confused because I thought I originally saw a .py file with code and the notebook was blank. But most recently a saw a notebook (.ipynb) but no .py module. I must be going crazy. Maybe I got confused with files stored in different directories? 

This looks great in most ways. I found the module code in a notebook, though, so I copied and pasted it into a .py file with the same name. Then everything ran great. Maybe take a quick look at how I restructured things so you can see the .py file and how it's imported in the notebook? I also moved everything into a folder with your name the exercises/exercise04 directory.

**Comment by aander222** [comment]
Chester,
Sorry for the late reply. The first time I submitted it there was a .py
module in an additional folder and a .ipynb file in the main folder, but
when I tried to redownload the .ipynb file the formatting seemed off. The
second time I submitted it I placed the .ipynb file and the .py module in
the same folder and renamed the .py module to include my last name.

I think that the way that I'm going about things is incorrect. I ran into
some runtime errors in colab so I used visual studio code then pasted my
code into the .ipynb file and pasted the .py module into google drive.
While I was able to write my program doing that I believe that copying
things over created some issues.

**Pull request merged**
