### PR TITLE
Exercise 1 & 2 Submission - Homayoon Aghili

### PR DESCRIPTION
**Pull request by Homie73**
Dear Dr. Harvey,

I hope that you are well. I saved a copy of my Google Drive copies of the exercise files in my branch and made this pull request. Additionally, I shared the Google Drive versions with you via email. Please let me know if there is an issue with your access to my assignments.

Best regards,
Homayoon Aghili

### CODE REVIEW

**Comment by chesterharvey** [comment]
Your code looks good! Glad to hear you worked your way through it on your own. I moved the notebook files into exercise directories and renamed them in the requested style.

**Comment by Homie73** [comment]
Thanks, Dr. Harvey.

I was so excited when I saw my code working that I forgot to check the
submission instructions. Excuse me for the carelessness.

Best,
Homayoon Aghili

**Comment by chesterharvey** [comment]
I'm glad your code worked, too! Nice job there.

**Comment by chesterharvey** [comment]
Also, great job writing specific functions for parts of the problem and then using them in a more general function. I said I would give a bonus for that, so +1.

**Pull request merged**
